// app-next/components/header/header.tsx
import { FunctionComponent } from "react"
import styles from "./header.module.sass"

const titleText = "August Saint Freytag"
const descriptors = ["Concept Designer", "Video Artist", "Developer", "Editor", "Storyteller"]
const descriptorSeparator = "/"
const descriptorText = descriptors.join(` ${descriptorSeparator} `)

const Header: FunctionComponent = () => (
	<header className={styles.header}>
		<section className={styles.leader}>
			<h1 className={styles.title}>{titleText}</h1>
			<div className={styles.descriptors}>{descriptorText}</div>
		</section>
		<nav className={styles.trailer}>
			<ol>
				<li>Home</li>
				<li>Life</li>
				<li>Work</li>
				<li>Imprint</li>
			</ol>
		</nav>
	</header>
)

export default Header

// components/header/header.vue
<template>
	<header>
		<div class="branding">
			<h1>{{ content.headerPrimaryTitle }}</h1>
			<section class="tagline">{{ content.headerPrimaryOccupations }}</section>
		</div>
		<div>
			<nav>
			</nav>
		</div>
	</header>
</template>

<style lang="scss" src="./header.scss"></style>

<script lang="ts">
	import { Component, Vue } from "vue-property-decorator"

	@Component
	export default class HeaderComponent extends Vue {
		data() {
			return {
				content: {
					headerPrimaryTitle: "August S. Freytag",
					headerPrimaryOccupations: ["Music Video Artist", "Editor", "Concept Designer", "Developer", "Analogue Photographer"].join(" ・ ")
				}
			}
		}
	}
</script>
